syntax = "proto3";

package agent.command;

message Request {
    oneof request {
        SelfDestroyRequest self_destroy = 1;
        HealthCheckRequest health_check = 2;
        ExecuteRequest execute = 3;
        GetFileRequest get_file = 4;
        PutFileRequest put_file = 5;
    }
}

message Response {
    oneof response {
        SelfDestroyResponse self_destroy = 1;
        HealthCheckResponse health_check = 2;
        ExecuteResponse execute = 3;
        GetFileResponse get_file = 4;
        PutFileResponse put_file = 5;
    }
}

message SelfDestroyRequest {}

message SelfDestroyResponse {}


message HealthCheckRequest {}

message HealthCheckResponse {}


message ExecuteRequest {
    string command = 1;
}

message ExecuteResponse {
    string output = 1;
}

message GetFileRequest {
    string path = 1;
    uint32 suggested_chunk_size = 2;
}

message GetFileResponse {}


message PutFileRequest {
    string path = 1;
}

message PutFileResponse {}
